services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8
    container_name: lista-tarefas-mysql
    environment:
      MYSQL_DATABASE: tarefasdb
      MYSQL_USER: tarefauser
      MYSQL_PASSWORD: tarefapass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Aplicação Spring Boot
  app:
    build: .
    container_name: lista-tarefas-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: tarefasdb
      DB_USER: tarefauser
      DB_PASSWORD: tarefapass
    depends_on:
      - mysql

volumes:
  mysql_data:
